import NavBar from '@/components/ui/Navbar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Mobile Shop',
  description: 'Generated by create next app',
};

export default async function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar />
      <main className="min-h-screen max-w-screen-xl	mx-auto">{children}</main>
    </div>
  );
}
